### ISSUE TITLE
TileAECapAdapter Causing a server craft

### ISSUE THREAD

**Issue by LittleWoglug** [ruifung/MECapabilityAdapter#5]
Hi,

We only just started using the adaptors on the server and we are starting to see this error in the debug logs with entity tracking related to TileAECapAdapter,

Pasted the stack trace below, Attached crash report

[18:41:54] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world entities
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: appeng.api.exceptions.SecurityConnectionException: Connection failed due to different security realms.
	at appeng.me.GridConnection.create(GridConnection.java:258) ~[GridConnection.class:?]
	at appeng.core.api.ApiGrid.createGridConnection(ApiGrid.java:62) ~[ApiGrid.class:?]
	at me.yrf.mcmods.capadapter.tiles.TileAECapAdapter$remoteLinkNode$2.invoke(TileAECapAdapter.kt:54) ~[TileAECapAdapter$remoteLinkNode$2.class:?]
	at me.yrf.mcmods.capadapter.tiles.TileAECapAdapter$remoteLinkNode$2.invoke(TileAECapAdapter.kt:31) ~[TileAECapAdapter$remoteLinkNode$2.class:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[SynchronizedLazyImpl.class:?]
	at me.yrf.mcmods.capadapter.tiles.TileAECapAdapter.getRemoteLinkNode(TileAECapAdapter.kt) ~[TileAECapAdapter.class:?]
	at me.yrf.mcmods.capadapter.tiles.TileAECapAdapter.onLoad(TileAECapAdapter.kt:162) ~[TileAECapAdapter.class:?]
	at net.minecraft.world.World.func_175700_a(World.java:1924) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1887) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
[18:41:54] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/smpicnic/server/data/./crash-reports/crash-2020-03-04_18.41.54-server.txt

If you need any more info please let me know
[crash-2020-03-04_18.41.54-server.txt](https://github.com/ruifung/MECapabilityAdapter/files/4289182/crash-2020-03-04_18.41.54-server.txt)

**Comment by ruifung** [comment]
... oof. Looks like I need to catch and handle that.
